AWSTemplateFormatVersion: "2010-09-09"
Description: Deploy ECS service components for a book-store on port 8080 with enhanced resources.

Parameters:
  PublicSubnetOneID:
    Type: String
    Default: subnet-0e2cc1721e990cfbc
  PublicSubnetTwoID:
    Type: String
    Default: subnet-0dd9f4df209bc1c91
  ECSSecurityGroupID:
    Type: String
    Default: sg-0e79f384f681e9d44
  VPCID:
    Type: String
    Description: "VPC ID where the target group and ECS should be deployed."
    Default: vpc-0e986d463eaaa6c83
  ApplicationLoadBalancerArn:
    Type: String
    Description: "ARN of the Application Load Balancer to be used for the ECS service."
    Default: arn:aws:elasticloadbalancing:ap-southeast-1:276662339380:loadbalancer/app/ecs-in-Appli-F1P8UIEyFw1v/8a74f6c26e15b0e2

Resources:
  ECSCluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: "book-store-cluster"

  TargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      Port: 8080
      Protocol: "HTTP"
      VpcId: !Ref VPCID
      TargetType: "ip"
      Matcher:
        HttpCode: "200"
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 300
      HealthCheckPath: "/"
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3

  ListenerRule:
    Type: "AWS::ElasticLoadBalancingV2::ListenerRule"
    Properties:
      ListenerArn: "arn:aws:elasticloadbalancing:ap-southeast-1:276662339380:listener/app/ecs-in-Appli-F1P8UIEyFw1v/8a74f6c26e15b0e2/9c79cfbb21bd02ac"
      Priority: 2
      Conditions:
        - Field: "path-pattern"
          Values: ["/book-store*"]
      Actions:
        - Type: "forward"
          TargetGroupArn: !Ref TargetGroup


  ECSTaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      Family: "book-store-task"
      Cpu: "512"
      Memory: "1024"
      NetworkMode: "awsvpc"
      RequiresCompatibilities:
        - "FARGATE"
      ExecutionRoleArn: "arn:aws:iam::276662339380:role/ecsTaskExecutionRole"
      ContainerDefinitions:
        - Name: "book-store-container"
          Image: 276662339380.dkr.ecr.ap-southeast-1.amazonaws.com/book-store-repo:latest
          Essential: true
          PortMappings:
            - ContainerPort: 8080
          Environment:
            - Name: "DB_HOST"
              Value: "bookstore-db.crmhgqdxqmag.ap-southeast-1.rds.amazonaws.com"
            - Name: "DB_PORT"
              Value: "5432"
            - Name: "DB_NAME"
              Value: "bookstore"
          Secrets:
            - Name: "DB_USERNAME"
              ValueFrom: !Sub "arn:aws:ssm:ap-southeast-1:276662339380:parameter/bookstore/db/username"
            - Name: "DB_PASSWORD"
              ValueFrom: !Sub "arn:aws:ssm:ap-southeast-1:276662339380:parameter/bookstore/db/password"
            - Name: "JWT_SECRET"
              ValueFrom: !Sub "arn:aws:ssm:ap-southeast-1:276662339380:parameter/bookstore/jwt_secret"

  ECSService:
    Type: "AWS::ECS::Service"
    DependsOn: "ECSTaskDefinition"
    Properties:
      ServiceName: "book-store-service"
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref ECSTaskDefinition
      DesiredCount: 1
      LaunchType: "FARGATE"
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !Ref PublicSubnetOneID
            - !Ref PublicSubnetTwoID
          SecurityGroups:
            - !Ref ECSSecurityGroupID
          AssignPublicIp: "ENABLED"
      LoadBalancers:
        - ContainerName: "book-store-container"
          ContainerPort: 8080
          TargetGroupArn: !Ref TargetGroup
